config/routes.rb
SampleApp::Application.routes.draw do

  resources :usersimulations

  resources :networks

  resources :loadtimes

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => "pages#home"

  match '/loadtimes', :to => 'iirst_pages#loadtimes'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/usersimulation.rb
class Usersimulation < ActiveRecord::Base
	attr_accessible :status, :interval, :numsims
	validates :status, :presence => true
	validates :interval, :presence => true
	validates :numsims, :presence => true
end

app/controllers/usersimulations_controller.rb
require 'rufus/scheduler'
require 'parallel'

class UsersimulationsController < ApplicationController
  # GET /usersimulations
  # GET /usersimulations.xml
  def index
    @usersimulations = Usersimulation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @usersimulations }
      
      scheduler = Rufus::Scheduler.start_new
      
      if @usersimulations.last.status.to_s == "true"
        x = @usersimulations.last.interval
        l = 0
        scheduler.every "#{x}s" do |job|
          if l >= 3
            puts "Stress testing finished running"
            job.unschedule
          else
            l += 1
            puts "Stress testing currently running"
            numsims = @usersimulations.last.numsims
            Parallel.each(1..numsims, :in_processes => numsims) do
              `java -jar selenium-server-standalone-2.31.0.jar -htmlSuite "*googlechrome" http://localhost:3000 mytestsuite.html results.html`
            end
		  end  		  
  		end
	  end
    end
  end

  # GET /usersimulations/1
  # GET /usersimulations/1.xml
  def show
    @usersimulation = Usersimulation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @usersimulation }
    end
  end

  # GET /usersimulations/new
  # GET /usersimulations/new.xml
  def new
    @usersimulation = Usersimulation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @usersimulation }
    end
  end

  # GET /usersimulations/1/edit
  def edit
    @usersimulation = Usersimulation.find(params[:id])
  end

  # POST /usersimulations
  # POST /usersimulations.xml
  def create
    @usersimulation = Usersimulation.new(params[:usersimulation])

    respond_to do |format|
      if @usersimulation.save
        format.html { redirect_to(@usersimulation, :notice => 'Usersimulation was successfully created.') }
        format.xml  { render :xml => @usersimulation, :status => :created, :location => @usersimulation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @usersimulation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /usersimulations/1
  # PUT /usersimulations/1.xml
  def update
    @usersimulation = Usersimulation.find(params[:id])

    respond_to do |format|
      if @usersimulation.update_attributes(params[:usersimulation])
        format.html { redirect_to(@usersimulation, :notice => 'Usersimulation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @usersimulation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /usersimulations/1
  # DELETE /usersimulations/1.xml
  def destroy
    @usersimulation = Usersimulation.find(params[:id])
    @usersimulation.destroy

    respond_to do |format|
      format.html { redirect_to(usersimulations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/usersimulations_helper.rb
module UsersimulationsHelper
end

app/views/usersimulations/_form.html.erb
<%= form_for(@usersimulation) do |f| %>
  <% if @usersimulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersimulation.errors.count, "error") %> prohibited this usersimulation from being saved:</h2>

      <ul>
      <% @usersimulation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :interval %><br />
    <%= f.text_field :interval %>
  </div>
  <div class="field">
    <%= f.label :numsims %><br />
    <%= f.text_field :numsims %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersimulations/edit.html.erb
<h1>Editing usersimulation</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersimulation %> |
<%= link_to 'Back', usersimulations_path %>

app/views/usersimulations/index.html.erb
<% if Network.last != nil %>
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>
<% end %>

<% if @usersimulations.last != nil %>
<h1>Current UserSim Settings</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Interval</th>
    <th>Numsims</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% x = @usersimulations.last %>
  <tr>
    <td><%= x.status %></td>
    <td><%= x.interval %></td>
    <td><%= x.numsims %></td>
  </tr>
</table>
<br />

<% end %>

<h1>Change User Simulation Settings</h1>
<% form_tag("/usersimulations", :method => "get") do %>
  <label for="status">Status (true or false): </label>
  <%= text_field_tag :status %>
  <br>
  <label for="interval">Interval (seconds): </label>
  <%= text_field_tag :interval %>
  <br>
  <label for="numsims">Numsims (how many users to emulate): </label>
  <%= text_field_tag :numsims %>
  <br>
 <%= submit_tag "Submit" %>
<% end %>
<br>

<% p = Usersimulation.new(:status => params[:status].to_s, :interval => params[:interval], :numsims => params[:numsims]) %>
<% p.save %>

app/views/usersimulations/new.html.erb
<h1>New usersimulation</h1>

<%= render 'form' %>

<%= link_to 'Back', usersimulations_path %>

app/views/usersimulations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @usersimulation.status %>
</p>

<p>
  <b>Interval:</b>
  <%= @usersimulation.interval %>
</p>

<p>
  <b>Numsims:</b>
  <%= @usersimulation.numsims %>
</p>


<%= link_to 'Edit', edit_usersimulation_path(@usersimulation) %> |
<%= link_to 'Back', usersimulations_path %>