config/routes.rb
SampleApp::Application.routes.draw do

  resources :usersimulations

  resources :networks

  resources :loadtimes

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => "pages#home"

  match '/loadtimes', :to => 'iirst_pages#loadtimes'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/loadtime.rb
class Loadtime < ActiveRecord::Base
  attr_accessible :loadtime, :page, :date
  validates :loadtime, :presence => true
  validates :page, :presence => true
  validates :date, :presence => true
end

app/controllers/loadtimes_controller.rb
class LoadtimesController < ApplicationController
  # GET /loadtimes
  # GET /loadtimes.xml
  def index
    @loadtimes = Loadtime.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @loadtimes }
    end
  end

  # GET /loadtimes/1
  # GET /loadtimes/1.xml
  def show
    @loadtime = Loadtime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @loadtime }
    end
  end

  # GET /loadtimes/new
  # GET /loadtimes/new.xml
  def new
    @loadtime = Loadtime.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @loadtime }
    end
  end

  # GET /loadtimes/1/edit
  def edit
    @loadtime = Loadtime.find(params[:id])
  end

  # POST /loadtimes
  # POST /loadtimes.xml
  def create
    @loadtime = Loadtime.new(params[:loadtime])

    respond_to do |format|
      if @loadtime.save
        format.html { redirect_to(@loadtime, :notice => 'Loadtime was successfully created.') }
        format.xml  { render :xml => @loadtime, :status => :created, :location => @loadtime }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @loadtime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /loadtimes/1
  # PUT /loadtimes/1.xml
  def update
    @loadtime = Loadtime.find(params[:id])

    respond_to do |format|
      if @loadtime.update_attributes(params[:loadtime])
        format.html { redirect_to(@loadtime, :notice => 'Loadtime was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @loadtime.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /loadtimes/1
  # DELETE /loadtimes/1.xml
  def destroy
    @loadtime = Loadtime.find(params[:id])
    @loadtime.destroy

    respond_to do |format|
      format.html { redirect_to(loadtimes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/loadtimes_helper.rb
module LoadtimesHelper
end

app/views/loadtimes/_form.html.erb
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>

<%= form_for(@loadtime) do |f| %>
  <% if @loadtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loadtime.errors.count, "error") %> prohibited this loadtime from being saved:</h2>

      <ul>
      <% @loadtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :loadtime %><br />
    <%= f.text_field :loadtime %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loadtimes/edit.html.erb
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>
<h1>Editing loadtime</h1>

<%= render 'form' %>

<%= link_to 'Show', @loadtime %> |
<%= link_to 'Back', loadtimes_path %>

app/views/loadtimes/index.html.erb
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>

<h1>Listing loadtimes</h1>

<% x = 0 %>
<% @loadtimes.each do |loadtime| %>
  <% x = x + loadtime.loadtime %>
<% end %>
<% x = x / @loadtimes.size %>
<h4> Average total loadtime: <%= x %> seconds </h4>

<table>
  <tr>
    <th>Loadtime</th>
    <th>Page</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% Loadtime.find(:all, :order => "id desc", :limit => 50).each do |loadtime| %>
  <tr>
    <td><%= loadtime.loadtime %></td>
    <td><%= loadtime.page %></td>
    <td><%= loadtime.date %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Loadtime', new_loadtime_path %>

app/views/loadtimes/new.html.erb
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>

<h1>New loadtime</h1>

<%= render 'form' %>

<%= link_to 'Back', loadtimes_path %>

app/views/loadtimes/show.html.erb
<% if Network.last.jitter.to_s == "true" %>
  <% sleep rand(Network.last.latency.to_i) %>
<% else sleep Network.last.latency.to_i %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Loadtime:</b>
  <%= @loadtime.loadtime %>
</p>

<p>
  <b>Page:</b>
  <%= @loadtime.page %>
</p>

<p>
  <b>Date:</b>
  <%= @loadtime.date %>
</p>


<%= link_to 'Edit', edit_loadtime_path(@loadtime) %> |
<%= link_to 'Back', loadtimes_path %>